'use client';

import { useState, useEffect } from 'react';
import { TextInput, NumberInput, Label, Badge, Switch, ButtonMinimal, Select, Slider, NameInput } from '@/gradian-ui/form-builder/form-elements';
import { Button } from '@/components/ui/button';
import { Trash2, Edit } from 'lucide-react';
import { FieldEditorProps } from '../types/builder';
import { ROLES } from '../utils/builder-utils';
import { fetchFormComponents } from '../utils/component-registry-client';
import { FormField } from '../types/form-schema';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { toCamelCase } from '@/gradian-ui/shared/utils/text-utils';
import { ComponentConfigEditor } from './ComponentConfigEditor';

export function FieldEditor({
  field,
  onUpdate,
  onDelete,
  sections,
  canMoveUp = false,
  canMoveDown = false,
  onMoveUp,
  onMoveDown,
  isIncomplete = false,
}: FieldEditorProps) {
  const [showDialog, setShowDialog] = useState(false);
  const [tempField, setTempField] = useState<Partial<FormField>>(field);
  const [nameManuallyEdited, setNameManuallyEdited] = useState(false);
  const [isNameCustom, setIsNameCustom] = useState(false);
  const [availableComponents, setAvailableComponents] = useState<Array<{ value: string; label: string; description?: string }>>([]);
  const [componentsLoading, setComponentsLoading] = useState(true);
  const [componentsError, setComponentsError] = useState<string | null>(null);

  // Fetch components from API - rigid access, no fallback
  useEffect(() => {
    const loadComponents = async () => {
      try {
        setComponentsLoading(true);
        setComponentsError(null);
        const components = await fetchFormComponents();
        setAvailableComponents(components);
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : 'Failed to load components';
        setComponentsError(errorMessage);
        console.error('Failed to load components from component registry:', error);
        // Don't set empty array - keep previous state or show error
      } finally {
        setComponentsLoading(false);
      }
    };

    loadComponents();
  }, []);

  useEffect(() => {
    setTempField(field);
    setNameManuallyEdited(false);
    setIsNameCustom(false);
  }, [field]);

  // Check if the label is invalid (empty, whitespace only, or "New Field")
  const isLabelInvalid = !tempField.label || 
                         tempField.label.trim() === '' || 
                         tempField.label.trim() === 'New Field';
  
  // Disable "Save" if label is invalid
  const canSave = !isLabelInvalid;

  const handleSave = () => {
    if (isLabelInvalid) {
      // Prevent save if label is invalid
      return;
    }
    onUpdate(tempField);
    setShowDialog(false);
  };

  const handleLabelChange = (value: string) => {
    const newLabel = value;
    let newName = tempField.name || '';
    
    // Auto-generate name from label if name hasn't been manually edited
    // or if the current name matches the auto-generated name from the old label
    if (!nameManuallyEdited) {
      const autoGeneratedName = toCamelCase(newLabel);
      if (autoGeneratedName) {
        newName = autoGeneratedName;
      }
    }
    
    setTempField({ ...tempField, label: newLabel, name: newName });
  };

  const handleNameChange = (value: string) => {
    setNameManuallyEdited(true);
    setTempField({ ...tempField, name: value });
  };


  return (
    <>
      <div className="w-full flex items-center justify-between">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-1.5">
            <span className={`text-sm font-medium truncate ${isIncomplete ? 'text-amber-700' : 'text-gray-800 dark:text-gray-200'}`}>
              {field.label || 'Unnamed Field'}
            </span>
            {isIncomplete && (
              <Badge variant="warning" size="sm" className="text-[10px] px-1.5 py-0">
                Incomplete
              </Badge>
            )}
            <Badge variant="outline" size="sm" className="text-[10px] px-1.5 py-0">{field.component}</Badge>
            {field.role && (
              <Badge variant="default" size="sm" className="text-[10px] px-1.5 py-0 bg-violet-100 text-violet-700 dark:bg-violet-900 dark:text-violet-200">
                {field.role}
              </Badge>
            )}
            {field.validation?.required && <Badge variant="danger" size="sm" className="text-[10px] px-1.5 py-0">Required</Badge>}
          </div>
          <span className={`text-[10px] truncate block mt-0.5 ${isIncomplete ? 'text-amber-600' : 'text-gray-400 dark:text-gray-300'}`}>
            {field.name}
          </span>
        </div>
        <div className="flex gap-0.5 ml-2 shrink-0">
          <ButtonMinimal
            icon={Edit}
            title="Edit Field"
            color="violet"
            size="md"
            onClick={() => setShowDialog(true)}
          />
          <ButtonMinimal
            icon={Trash2}
            title="Delete Field"
            color="red"
            size="md"
            onClick={onDelete}
          />
        </div>
      </div>

      {showDialog && (
        <Dialog open={showDialog} onOpenChange={(open) => !open && setShowDialog(false)}>
          <DialogContent className="w-[95vw] sm:w-full max-w-3xl max-h-[90vh] flex flex-col p-0 rounded-2xl">
            <DialogHeader className="px-6 pt-6 pb-4 border-b border-gray-100 dark:border-gray-700 shrink-0">
              <DialogTitle>Edit Field</DialogTitle>
              <DialogDescription>
                Configure field properties and settings
              </DialogDescription>
            </DialogHeader>
            <div className="flex-1 overflow-y-auto px-6">
              <div className="space-y-5 py-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <TextInput
                    config={{
                      name: 'label',
                      label: 'Field Label',
                      type: 'text',
                      placeholder: 'Enter field label...'
                    }}
                    value={tempField.label || ''}
                    onChange={handleLabelChange}
                    className="h-9"
                  />
                  {isLabelInvalid && (
                    <p className="text-xs text-amber-600 mt-1.5">
                      Please enter a valid field label (cannot be empty or "New Field").
                    </p>
                  )}
                </div>
                <NameInput
                  config={{ 
                    name: 'field-name', 
                    label: 'Field Name',
                    placeholder: 'Auto-generated from label'
                  }}
                  value={tempField.name || ''}
                  onChange={handleNameChange}
                  isCustomizable
                  customMode={isNameCustom}
                  onCustomModeChange={(custom) => {
                    setIsNameCustom(custom);
                    if (!custom) {
                      // Reset to auto-generated name when turning customization off
                      const autoGeneratedName = toCamelCase(tempField.label || '');
                      setTempField((current) => ({
                        ...current,
                        name: autoGeneratedName || current?.name || '',
                      }));
                      setNameManuallyEdited(false);
                    }
                  }}
                  customizeDisabled={false}
                  helperText={!isNameCustom ? 'Field name auto-generates from the label. Click "Customize" to override.' : undefined}
                  className="h-9"
                />
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <Label className="text-xs font-medium text-gray-700 mb-1.5 block">Component</Label>
                  {componentsError ? (
                    <div className="space-y-1.5">
                      <Select
                        value={tempField.component || ''}
                        onValueChange={(value) => {
                          setTempField({ 
                            ...tempField, 
                            component: value as any,
                            componentTypeConfig: undefined 
                          });
                        }}
                        options={availableComponents.map((comp) => ({ value: comp.value, label: comp.label }))}
                        sortType="ASC"
                        disabled={true}
                      />
                      <p className="text-xs text-red-600 dark:text-red-400">
                        Error loading components: {componentsError}
                      </p>
                    </div>
                  ) : (
                    <>
                      <Select
                        value={tempField.component || ''}
                        onValueChange={(value) => {
                          // Reset componentTypeConfig when component type changes
                          setTempField({ 
                            ...tempField, 
                            component: value as any,
                            componentTypeConfig: undefined 
                          });
                        }}
                        options={availableComponents.map((comp) => ({ value: comp.value, label: comp.label }))}
                        sortType="ASC"
                        disabled={componentsLoading}
                      />
                      {!componentsLoading && availableComponents.length > 0 && tempField.component && (
                        <p className="text-xs text-gray-500 mt-1.5">
                          {availableComponents.find(c => c.value === tempField.component)?.description || ''}
                        </p>
                      )}
                      {componentsLoading && (
                        <p className="text-xs text-gray-500 mt-1.5">Loading components...</p>
                      )}
                    </>
                  )}
                </div>
                <div>
                  <Label className="text-xs font-medium text-gray-700 mb-1.5 block">Section</Label>
                  <Select
                    value={tempField.sectionId || ''}
                    onValueChange={(value) => setTempField({ ...tempField, sectionId: value })}
                    options={sections.map((section) => ({ value: section.id, label: section.title }))}
                  />
                </div>
              </div>
              <div>
                <TextInput
                  config={{
                    name: 'placeholder',
                    label: 'Placeholder',
                    type: 'text',
                    placeholder: 'Enter placeholder text...'
                  }}
                  value={tempField.placeholder || ''}
                  onChange={(value) => setTempField({ ...tempField, placeholder: value })}
                  className="h-9"
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label className="text-xs font-medium text-gray-700 mb-1.5 block">Role</Label>
                  <Select
                    value={tempField.role || ''}
                    onValueChange={(value) => setTempField({ ...tempField, role: value ? (value as any) : undefined })}
                    options={[
                      { value: '', label: 'None' },
                      ...ROLES.map((role) => ({ value: role.value, label: role.label }))
                    ]}
                    sortType="ASC"
                  />
                </div>
                <div>
                  <Label className="text-xs font-medium text-gray-700 mb-1.5 block">Role Color</Label>
                  <Select
                    value={tempField.roleColor || ''}
                    onValueChange={(value) => setTempField({ ...tempField, roleColor: value ? (value as any) : undefined })}
                    options={[
                      { value: '', label: 'Default' },
                      { value: 'default', label: 'Default' },
                      { value: 'secondary', label: 'Secondary' },
                      { value: 'outline', label: 'Outline' },
                      { value: 'destructive', label: 'Destructive' },
                      { value: 'gradient', label: 'Gradient' },
                      { value: 'success', label: 'Success' },
                      { value: 'warning', label: 'Warning' },
                      { value: 'info', label: 'Info' },
                      { value: 'muted', label: 'Muted' },
                    ]}
                  />
                </div>
              </div>
              <div>
                <Slider
                  config={{
                    name: 'colSpan',
                    label: 'Column Span',
                  }}
                  value={tempField.colSpan || 1}
                  onChange={(value) => setTempField({ ...tempField, colSpan: value })}
                  min={1}
                  max={4}
                  step={1}
                />
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 gap-4">
                <Switch
                  config={{ name: `required-${field.id}`, label: 'Required' }}
                  checked={tempField.validation?.required || false}
                  onChange={(checked) => setTempField({ 
                    ...tempField, 
                    validation: { 
                      ...tempField.validation, 
                      required: checked 
                    } 
                  })}
                />
                <Switch
                  config={{ name: `disabled-${field.id}`, label: 'Disabled' }}
                  checked={tempField.disabled || false}
                  onChange={(checked) => setTempField({ ...tempField, disabled: checked })}
                />
                <Switch
                  config={{ name: `readonly-${field.id}`, label: 'Readonly' }}
                  checked={tempField.readonly || false}
                  onChange={(checked) => setTempField({ ...tempField, readonly: checked })}
                />
                <Switch
                  config={{ name: `canCopy-${field.id}`, label: 'Can Copy' }}
                  checked={tempField.canCopy || false}
                  onChange={(checked) => setTempField({ ...tempField, canCopy: checked })}
                />
                <Switch
                  config={{ name: `inactive-${field.id}`, label: 'Inactive' }}
                  checked={tempField.inactive || false}
                  onChange={(checked) => setTempField({ ...tempField, inactive: checked })}
                />
                <Switch
                  config={{ name: `addToReferenceMetadata-${field.id}`, label: 'Add To Reference Metadata' }}
                  checked={tempField.addToReferenceMetadata || false}
                  onChange={(checked) => setTempField({ ...tempField, addToReferenceMetadata: checked })}
                />
              </div>
              {tempField.component && (
                <ComponentConfigEditor
                  componentType={tempField.component}
                  config={tempField.componentTypeConfig}
                  onChange={(newConfig) => setTempField({ ...tempField, componentTypeConfig: newConfig })}
                />
              )}
              </div>
            </div>
            <DialogFooter className="px-6 pt-4 pb-6 border-t border-gray-100 dark:border-gray-700 shrink-0 flex-col sm:flex-row gap-2">
              <Button variant="outline" onClick={() => setShowDialog(false)} className="w-full sm:w-auto text-sm md:text-base">
                Cancel
              </Button>
              <Button onClick={handleSave} disabled={!canSave} className="w-full sm:w-auto text-sm md:text-base">
                <span className="hidden md:inline">Save Changes</span>
                <span className="md:hidden">Save</span>
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}
    </>
  );
}

