'use client';

import React, { forwardRef, useImperativeHandle, useMemo, useRef, useState } from 'react';
import { CheckCircle } from 'lucide-react';
import { cn, validateField } from '../../../shared/utils';
import { baseInputClasses, getLabelClasses } from '../utils/field-styles';
import { FormElementRef, NameInputProps } from '../types';
import { CopyContent } from './CopyContent';
import { loggingCustom } from '@/gradian-ui/shared/utils/logging-custom';
import { LogType } from '@/gradian-ui/shared/configs/log-config';
import { getT, getDefaultLanguage } from '@/gradian-ui/shared/utils/translation-utils';
import { useLanguageStore } from '@/stores/language.store';
import { TRANSLATION_KEYS } from '@/gradian-ui/shared/constants/translations';

const allowedPattern = /^[a-z0-9_-]+$/;

export const NameInput = forwardRef<FormElementRef, NameInputProps>(
  (
    {
      config,
      value = '',
      onChange,
      onBlur,
      onFocus,
      error,
      disabled = false,
      required = false,
      placeholder,
      className,
      forbiddenSymbolsMessage = 'Lowercase, numbers, hyphens(-), and underscores(_) are allowed.',
      isCustomizable = false,
      customMode: customModeProp,
      defaultCustomMode = false,
      onCustomModeChange,
      customizeDisabled = false,
      helperText,
      touched,
      canCopy = false,
      ...props
    },
    ref
  ) => {
    const inputRef = useRef<HTMLInputElement>(null);
    const language = useLanguageStore((s) => s.language) || getDefaultLanguage();
    const defaultLang = getDefaultLanguage();
    const labelCustomize = getT(TRANSLATION_KEYS.LABEL_CUSTOMIZE, language, defaultLang);
    const labelUseGenerated = getT(TRANSLATION_KEYS.LABEL_USE_GENERATED, language, defaultLang);
    const msgAutoGeneratedClickCustomize = getT(TRANSLATION_KEYS.MSG_AUTO_GENERATED_CLICK_CUSTOMIZE, language, defaultLang);

    const fieldName = config?.name || config?.id || 'name';
    const fieldLabel = config?.label;
    const fieldPlaceholder = placeholder || config?.placeholder;

    const isControlledCustomMode = typeof customModeProp === 'boolean';
    const [internalCustomMode, setInternalCustomMode] = useState(defaultCustomMode);
    const isCustomMode = isControlledCustomMode ? customModeProp! : internalCustomMode;

    const handleCustomModeToggle = () => {
      if (!isCustomizable || disabled || customizeDisabled) return;
      const next = !isCustomMode;
      if (!isControlledCustomMode) {
        setInternalCustomMode(next);
      }
      onCustomModeChange?.(next);
    };

    useImperativeHandle(ref, () => ({
      focus: () => inputRef.current?.focus(),
      blur: () => inputRef.current?.blur(),
      validate: () => {
        if (!config?.validation) {
          return required ? allowedPattern.test(String(value)) : true;
        }
        const result = validateField(value, config.validation);
        return result.isValid && (config.validation?.pattern ? true : allowedPattern.test(String(value)));
      },
      reset: () => onChange?.(''),
      getValue: () => value,
      setValue: (newValue) => onChange?.(sanitize(newValue ?? '')),
    }));

    const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
      if (disabled || (isCustomizable && !isCustomMode)) return;
      const sanitizedValue = sanitize(event.target.value);
      if (sanitizedValue !== event.target.value) {
        event.target.value = sanitizedValue;
      }
      onChange?.(sanitizedValue);
    };

    const handleBlur = () => {
      onBlur?.();
    };

    const handleFocus = () => {
      onFocus?.();
    };

    const isValidName = useMemo(() => Boolean(value) && allowedPattern.test(String(value)), [value]);

    const hasValue = Boolean(value);
    const showCheckCircle = isValidName && !error;
    const showCopyButton = canCopy && hasValue;
    const rightPadding = showCopyButton && showCheckCircle ? 'pe-20' : (showCopyButton || showCheckCircle ? 'pe-10' : '');

    const inputClasses = cn(
      baseInputClasses,
      error ? 'border-red-500 focus-visible:ring-red-300 focus-visible:border-red-500 dark:border-red-500 dark:focus-visible:ring-red-400 dark:focus-visible:border-red-500' : '',
      rightPadding,
      className
    );

    if (!config) {
      loggingCustom(LogType.CLIENT_LOG, 'error', 'NameInput: config is required');
      return null;
    }

    const computedDisabled = disabled || (isCustomizable && !isCustomMode);
    const showHelperText = helperText ?? (isCustomizable && !isCustomMode
      ? msgAutoGeneratedClickCustomize
      : forbiddenSymbolsMessage);

    const labelEl = fieldLabel ? (
      <label
        htmlFor={fieldName}
        className={getLabelClasses({
          error: Boolean(error),
          required: required ?? config?.required ?? config?.validation?.required ?? false,
        })}
      >
        {fieldLabel}
      </label>
    ) : null;

    return (
      <div className="w-full">
        {isCustomizable ? (
          <div className="flex items-center justify-between gap-2 mb-2">
            {labelEl ?? <span />}
            <button
              type="button"
              onClick={handleCustomModeToggle}
              disabled={disabled || customizeDisabled}
              className={cn(
                'h-7 px-2 text-xs font-medium rounded-md border border-transparent transition-colors',
                'bg-transparent text-violet-600 hover:bg-violet-50 disabled:text-gray-400 disabled:hover:bg-transparent'
              )}
            >
              {isCustomMode ? labelUseGenerated : labelCustomize}
            </button>
          </div>
        ) : (
          labelEl
        )}

        <div className="relative">
          <input
            ref={inputRef}
            id={fieldName}
            name={fieldName}
            type="text"
            value={value ?? ''}
            onChange={handleChange}
            onBlur={handleBlur}
            onFocus={handleFocus}
            placeholder={fieldPlaceholder}
            required={required ?? config?.required ?? config?.validation?.required ?? false}
            disabled={computedDisabled}
            autoComplete="off"
            dir="ltr"
            className={inputClasses}
            {...props}
          />

          <div className="absolute right-1 top-1/2 -translate-y-1/2 flex items-center gap-1">
            {canCopy && hasValue && (
              <CopyContent content={value} />
            )}
            {showCheckCircle && (
              <CheckCircle className="h-4 w-4 text-emerald-500" />
            )}
          </div>
        </div>

        {error ? (
          <p className="mt-1 text-xs text-red-600 dark:text-red-400" role="alert">
            {error}
          </p>
        ) : showHelperText ? (
          <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">{showHelperText}</p>
        ) : null}
      </div>
    );
  }
);

NameInput.displayName = 'NameInput';

function sanitize(rawValue: string): string {
  return rawValue
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9@._-]/g, '') // Allow @ and .
    .replace(/-+/g, '-')
    .replace(/^-+/, '')
    .replace(/-+$/, '');
}