import receiptline from "receiptline";
import type { PrinterConfig, ReceiptLineDoc } from "../types";

/** Heat-printer-oriented defaults for browser SVG preview (no cutting). */
export const DEFAULT_PRINTER_CONFIG: Readonly<Partial<PrinterConfig>> = {
  command: "svg",
  cpl: 48,
  encoding: "multilingual",
  spacing: false,
  cutting: false,
  gradient: false,
  gamma: 1.8,
  threshold: 128,
  upsideDown: false,
  margin: 0,
  marginRight: 0,
};

/**
 * Extra horizontal pixels to add per character (receiptline uses fixed charWidth).
 * Set to 0 to preserve the column layout generated by receiptline exactly.
 */
const SVG_LETTER_SPACING_PX = 0;

/**
 * Post-process SVG: add extra horizontal spacing to each character by increasing
 * each <tspan x="N"> within every <text> by (characterIndex * extraPx).
 * receiptline positions characters with fixed charWidth; CSS letter-spacing has no effect.
 */
function addSvgLetterSpacing(svg: string, extraPx: number = SVG_LETTER_SPACING_PX): string {
  if (!svg || extraPx <= 0) return svg;
  return svg.replace(/<text[^>]*>([\s\S]*?)<\/text>/gi, (textMatch, inner) => {
    let index = 0;
    const newInner = inner.replace(/<tspan\s+([^>]*?)x="(\d+)"([^>]*)>/gi, (_m: string, before: string, xStr: string, after: string) => {
      const x = Number.parseInt(xStr, 10);
      const newX = x + index * extraPx;
      index += 1;
      return `<tspan ${before}x="${newX}"${after}>`;
    });
    return textMatch.replace(inner, newInner);
  });
}

/**
 * Transforms a ReceiptLine document to an SVG string for display or print.
 * Uses heat-printer-friendly defaults; pass printerConfig to override.
 * Post-processes the SVG to add letter spacing (receiptline uses fixed character positions).
 *
 * @param doc - ReceiptLine document string
 * @param printer - Optional partial printer config (merged with defaults)
 * @returns SVG string, or empty string on error
 */
export function transformDocToSvg(
  doc: ReceiptLineDoc,
  printer?: Partial<PrinterConfig>
): string {
  if (typeof doc !== "string" || doc.trim().length === 0) {
    return "";
  }
  try {
    const config: PrinterConfig = {
      ...DEFAULT_PRINTER_CONFIG,
      ...printer,
    };
    const result = receiptline.transform(doc, config);
    const svg = typeof result === "string" ? result : "";
    return svg ? addSvgLetterSpacing(svg) : "";
  } catch {
    return "";
  }
}
